ALTER TABLE i2b2demodata.observation_fact DROP CONSTRAINT observation_fact_pk;
DROP INDEX i2b2demodata.OF_IDX_ClusteredConcept;
DROP INDEX i2b2demodata.OF_IDX_ALLObservation_Fact;
DROP INDEX i2b2demodata.OF_IDX_Start_Date;
DROP INDEX i2b2demodata.OF_IDX_Modifier;
DROP INDEX i2b2demodata.OF_IDX_Encounter_Patient;
DROP INDEX i2b2demodata.OF_IDX_UPLOADID;
DROP INDEX i2b2demodata.OF_IDX_SOURCESYSTEM_CD;
DROP INDEX i2b2demodata.OF_TEXT_SEARCH_UNIQUE;
TRUNCATE i2b2demodata.observation_fact;
CREATE TABLE i2b2demodata.observation_fact_b2007 (
    CHECK ( start_date < TIMESTAMP '2007-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2007 (
    CHECK ( start_date >= TIMESTAMP '2007-01-01 00:00:00' AND start_date < TIMESTAMP '2008-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2008 (
    CHECK ( start_date >= TIMESTAMP '2008-01-01 00:00:00' AND start_date < TIMESTAMP '2009-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2009 (
    CHECK ( start_date >= TIMESTAMP '2009-01-01 00:00:00' AND start_date < TIMESTAMP '2010-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2010 (
    CHECK ( start_date >= TIMESTAMP '2010-01-01 00:00:00' AND start_date < TIMESTAMP '2011-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2011 (
    CHECK ( start_date >= TIMESTAMP '2011-01-01 00:00:00' AND start_date < TIMESTAMP '2012-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2012 (
    CHECK ( start_date >= TIMESTAMP '2012-01-01 00:00:00' AND start_date < TIMESTAMP '2013-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2013 (
    CHECK ( start_date >= TIMESTAMP '2013-01-01 00:00:00' AND start_date < TIMESTAMP '2014-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2014 (
    CHECK ( start_date >= TIMESTAMP '2014-01-01 00:00:00' AND start_date < TIMESTAMP '2015-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2015 (
    CHECK ( start_date >= TIMESTAMP '2015-01-01 00:00:00' AND start_date < TIMESTAMP '2016-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2016 (
    CHECK ( start_date >= TIMESTAMP '2016-01-01 00:00:00' AND start_date < TIMESTAMP '2017-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_2017 (
    CHECK ( start_date >= TIMESTAMP '2017-01-01 00:00:00' AND start_date < TIMESTAMP '2018-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);
CREATE TABLE i2b2demodata.observation_fact_a2017 (
    CHECK ( start_date >= TIMESTAMP '2018-01-01 00:00:00' )
) INHERITS (i2b2demodata.observation_fact);

CREATE OR REPLACE FUNCTION observation_fact_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF ( NEW.start_date < TIMESTAMP '2007-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_b2007 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2007-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2008-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2007 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2008-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2009-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2008 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2009-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2010-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2009 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2010-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2011-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2010 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2011-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2012-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2011 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2012-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2013-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2012 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2013-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2014-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2013 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2014-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2015-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2014 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2015-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2016-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2015 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2016-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2017-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2016 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2017-01-01 00:00:00' AND
            NEW.start_date < TIMESTAMP '2018-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_2017 VALUES (NEW.*);
    ELSIF ( NEW.start_date >= TIMESTAMP '2018-01-01 00:00:00' ) THEN
        INSERT INTO i2b2demodata.observation_fact_a2017 VALUES (NEW.*);
    ELSE
        RAISE EXCEPTION 'Date out of range.  Fix the observation_fact_insert_trigger() function!';
    END IF;
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;
CREATE TRIGGER insert_observation_fact_trigger
    BEFORE INSERT ON i2b2demodata.observation_fact
    FOR EACH ROW EXECUTE PROCEDURE observation_fact_insert_trigger();
SET constraint_exclusion = on; 
COPY i2b2demodata.observation_fact(ENCOUNTER_NUM, PATIENT_NUM, CONCEPT_CD, PROVIDER_ID, START_DATE, MODIFIER_CD, INSTANCE_NUM, VALTYPE_CD, TVAL_CHAR, NVAL_NUM, VALUEFLAG_CD, QUANTITY_NUM, UNITS_CD, END_DATE, LOCATION_CD, OBSERVATION_BLOB, CONFIDENCE_NUM, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID) FROM '/home/ubuntu/Datensatz/csv/observation_fact.csv' DELIMITER '|' CSV;
ALTER TABLE i2b2demodata.observation_fact ADD CONSTRAINT observation_fact_pk PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_b2007 ADD CONSTRAINT observation_fact_pk_b2007 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2007 ADD CONSTRAINT observation_fact_pk_2007 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2008 ADD CONSTRAINT observation_fact_pk_2008 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2009 ADD CONSTRAINT observation_fact_pk_2009 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2010 ADD CONSTRAINT observation_fact_pk_2010 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2011 ADD CONSTRAINT observation_fact_pk_2011 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2012 ADD CONSTRAINT observation_fact_pk_2012 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2013 ADD CONSTRAINT observation_fact_pk_2013 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2014 ADD CONSTRAINT observation_fact_pk_2014 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2015 ADD CONSTRAINT observation_fact_pk_2015 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2016 ADD CONSTRAINT observation_fact_pk_2016 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_2017 ADD CONSTRAINT observation_fact_pk_2017 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);
ALTER TABLE i2b2demodata.observation_fact_a2017 ADD CONSTRAINT observation_fact_pk_a2017 PRIMARY KEY (PATIENT_NUM, CONCEPT_CD, MODIFIER_CD, START_DATE, ENCOUNTER_NUM, INSTANCE_NUM, PROVIDER_ID);

CREATE  INDEX OF_IDX_ClusteredConcept_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_b2007 ON i2b2demodata.OBSERVATION_FACT_b2007(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2007 ON i2b2demodata.OBSERVATION_FACT_2007
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2007 ON i2b2demodata.OBSERVATION_FACT_2007
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2007 ON i2b2demodata.OBSERVATION_FACT_2007(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2007 ON i2b2demodata.OBSERVATION_FACT_2007(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2007 ON i2b2demodata.OBSERVATION_FACT_2007(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2007 ON i2b2demodata.OBSERVATION_FACT_2007(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2007 ON i2b2demodata.OBSERVATION_FACT_2007(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2007 ON i2b2demodata.OBSERVATION_FACT_2007(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2008 ON i2b2demodata.OBSERVATION_FACT_2008
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2008 ON i2b2demodata.OBSERVATION_FACT_2008
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2008 ON i2b2demodata.OBSERVATION_FACT_2008(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2008 ON i2b2demodata.OBSERVATION_FACT_2008(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2008 ON i2b2demodata.OBSERVATION_FACT_2008(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2008 ON i2b2demodata.OBSERVATION_FACT_2008(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2008 ON i2b2demodata.OBSERVATION_FACT_2008(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2008 ON i2b2demodata.OBSERVATION_FACT_2008(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2009 ON i2b2demodata.OBSERVATION_FACT_2009
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2009 ON i2b2demodata.OBSERVATION_FACT_2009
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2009 ON i2b2demodata.OBSERVATION_FACT_2009(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2009 ON i2b2demodata.OBSERVATION_FACT_2009(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2009 ON i2b2demodata.OBSERVATION_FACT_2009(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2009 ON i2b2demodata.OBSERVATION_FACT_2009(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2009 ON i2b2demodata.OBSERVATION_FACT_2009(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2009 ON i2b2demodata.OBSERVATION_FACT_2009(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2010 ON i2b2demodata.OBSERVATION_FACT_2010
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2010 ON i2b2demodata.OBSERVATION_FACT_2010
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2010 ON i2b2demodata.OBSERVATION_FACT_2010(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2010 ON i2b2demodata.OBSERVATION_FACT_2010(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2010 ON i2b2demodata.OBSERVATION_FACT_2010(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2010 ON i2b2demodata.OBSERVATION_FACT_2010(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2010 ON i2b2demodata.OBSERVATION_FACT_2010(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2010 ON i2b2demodata.OBSERVATION_FACT_2010(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2011 ON i2b2demodata.OBSERVATION_FACT_2011
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2011 ON i2b2demodata.OBSERVATION_FACT_2011
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2011 ON i2b2demodata.OBSERVATION_FACT_2011(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2011 ON i2b2demodata.OBSERVATION_FACT_2011(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2011 ON i2b2demodata.OBSERVATION_FACT_2011(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2011 ON i2b2demodata.OBSERVATION_FACT_2011(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2011 ON i2b2demodata.OBSERVATION_FACT_2011(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2011 ON i2b2demodata.OBSERVATION_FACT_2011(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2012 ON i2b2demodata.OBSERVATION_FACT_2012
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2012 ON i2b2demodata.OBSERVATION_FACT_2012
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2012 ON i2b2demodata.OBSERVATION_FACT_2012(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2012 ON i2b2demodata.OBSERVATION_FACT_2012(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2012 ON i2b2demodata.OBSERVATION_FACT_2012(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2012 ON i2b2demodata.OBSERVATION_FACT_2012(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2012 ON i2b2demodata.OBSERVATION_FACT_2012(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2012 ON i2b2demodata.OBSERVATION_FACT_2012(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2013 ON i2b2demodata.OBSERVATION_FACT_2013
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2013 ON i2b2demodata.OBSERVATION_FACT_2013
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2013 ON i2b2demodata.OBSERVATION_FACT_2013(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2013 ON i2b2demodata.OBSERVATION_FACT_2013(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2013 ON i2b2demodata.OBSERVATION_FACT_2013(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2013 ON i2b2demodata.OBSERVATION_FACT_2013(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2013 ON i2b2demodata.OBSERVATION_FACT_2013(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2013 ON i2b2demodata.OBSERVATION_FACT_2013(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2014 ON i2b2demodata.OBSERVATION_FACT_2014
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2014 ON i2b2demodata.OBSERVATION_FACT_2014
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2014 ON i2b2demodata.OBSERVATION_FACT_2014(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2014 ON i2b2demodata.OBSERVATION_FACT_2014(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2014 ON i2b2demodata.OBSERVATION_FACT_2014(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2014 ON i2b2demodata.OBSERVATION_FACT_2014(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2014 ON i2b2demodata.OBSERVATION_FACT_2014(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2014 ON i2b2demodata.OBSERVATION_FACT_2014(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2015 ON i2b2demodata.OBSERVATION_FACT_2015
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2015 ON i2b2demodata.OBSERVATION_FACT_2015
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2015 ON i2b2demodata.OBSERVATION_FACT_2015(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2015 ON i2b2demodata.OBSERVATION_FACT_2015(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2015 ON i2b2demodata.OBSERVATION_FACT_2015(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2015 ON i2b2demodata.OBSERVATION_FACT_2015(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2015 ON i2b2demodata.OBSERVATION_FACT_2015(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2015 ON i2b2demodata.OBSERVATION_FACT_2015(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2016 ON i2b2demodata.OBSERVATION_FACT_2016
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2016 ON i2b2demodata.OBSERVATION_FACT_2016
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2016 ON i2b2demodata.OBSERVATION_FACT_2016(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2016 ON i2b2demodata.OBSERVATION_FACT_2016(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2016 ON i2b2demodata.OBSERVATION_FACT_2016(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2016 ON i2b2demodata.OBSERVATION_FACT_2016(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2016 ON i2b2demodata.OBSERVATION_FACT_2016(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2016 ON i2b2demodata.OBSERVATION_FACT_2016(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_2017 ON i2b2demodata.OBSERVATION_FACT_2017
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_2017 ON i2b2demodata.OBSERVATION_FACT_2017
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_2017 ON i2b2demodata.OBSERVATION_FACT_2017(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_2017 ON i2b2demodata.OBSERVATION_FACT_2017(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_2017 ON i2b2demodata.OBSERVATION_FACT_2017(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_2017 ON i2b2demodata.OBSERVATION_FACT_2017(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_2017 ON i2b2demodata.OBSERVATION_FACT_2017(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_2017 ON i2b2demodata.OBSERVATION_FACT_2017(TEXT_SEARCH_INDEX);

CREATE  INDEX OF_IDX_ClusteredConcept_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017
(
    CONCEPT_CD 
);


CREATE INDEX OF_IDX_ALLObservation_Fact_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017
(
    PATIENT_NUM ,
    ENCOUNTER_NUM ,
    CONCEPT_CD ,
    START_DATE ,
    PROVIDER_ID ,
    MODIFIER_CD ,
    INSTANCE_NUM,
    VALTYPE_CD ,
    TVAL_CHAR ,
    NVAL_NUM ,
    VALUEFLAG_CD ,
    QUANTITY_NUM ,
    UNITS_CD ,
    END_DATE ,
    LOCATION_CD ,
    CONFIDENCE_NUM
);

CREATE INDEX OF_IDX_Start_Date_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(START_DATE, PATIENT_NUM);
CREATE INDEX OF_IDX_Modifier_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(MODIFIER_CD);
CREATE INDEX OF_IDX_Encounter_Patient_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(ENCOUNTER_NUM, PATIENT_NUM, INSTANCE_NUM);
CREATE INDEX OF_IDX_UPLOADID_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(UPLOAD_ID);
CREATE INDEX OF_IDX_SOURCESYSTEM_CD_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(SOURCESYSTEM_CD);
CREATE UNIQUE INDEX OF_TEXT_SEARCH_UNIQUE_a2017 ON i2b2demodata.OBSERVATION_FACT_a2017(TEXT_SEARCH_INDEX);
