DELETE FROM i2b2metadata.EVA_META WHERE C_FULLNAME LIKE '\\Stammdaten\\Sex\\%';
INSERT INTO i2b2metadata.EVA_META (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, M_APPLIED_PATH, UPDATE_DATE, C_PATH)
  VALUES (1, '\Stammdaten\Sex\', 'Geschlecht', 'N', 'CA', NULL, NULL, '', '', '', '', '', '', '', '2014-01-01', NULL);
INSERT INTO i2b2metadata.EVA_META (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, M_APPLIED_PATH, UPDATE_DATE, C_PATH)
  VALUES (2, '\Stammdaten\Sex\m\', 'Männlich', 'N', 'LA', NULL, NULL, 'PATIENT_NUM', 'PATIENT_DIMENSION', 'SEX_CD', 'T', '=', '2', '', '2014-01-01', NULL);
INSERT INTO i2b2metadata.EVA_META (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, M_APPLIED_PATH, UPDATE_DATE, C_PATH)
  VALUES (2, '\Stammdaten\Sex\w\', 'Weiblich', 'N', 'LA', NULL, NULL, 'PATIENT_NUM', 'PATIENT_DIMENSION', 'SEX_CD', 'T', '=', '1', '', '2014-01-01', NULL);
