DROP TABLE IF EXISTS i2b2metadata.EVA_META;
DROP TABLE IF EXISTS EVA_META;
DROP INDEX IF EXISTS META_FULLNAME_IDX_eva_meta;
DROP INDEX IF EXISTS META_APPLIED_PATH_IDX_eva_meta;

CREATE TABLE i2b2metadata.EVA_META
   (	
    C_HLEVEL INT					NOT NULL, 
	C_FULLNAME VARCHAR(700)			NOT NULL, 
	C_NAME VARCHAR(2000)			NOT NULL, 
	C_SYNONYM_CD CHAR(1)			NOT NULL, 
	C_VISUALATTRIBUTES CHAR(3)		NOT NULL, 
	C_TOTALNUM INT					NULL, 
	C_BASECODE VARCHAR(50)			NULL, 
	C_METADATAXML TEXT				NULL, 
	C_FACTTABLECOLUMN VARCHAR(50)	NOT NULL, 
	C_TABLENAME VARCHAR(50)			NOT NULL, 
	C_COLUMNNAME VARCHAR(50)		NOT NULL, 
	C_COLUMNDATATYPE VARCHAR(50)	NOT NULL, 
	C_OPERATOR VARCHAR(10)			NOT NULL, 
	C_DIMCODE VARCHAR(700)			NOT NULL, 
	C_COMMENT TEXT					NULL, 
	C_TOOLTIP VARCHAR(900)			NULL, 
	M_APPLIED_PATH VARCHAR(700)		NOT NULL, 
	UPDATE_DATE timestamp			NOT NULL, 
	DOWNLOAD_DATE timestamp			NULL, 
	IMPORT_DATE timestamp			NULL, 
	SOURCESYSTEM_CD VARCHAR(50)		NULL, 
	VALUETYPE_CD VARCHAR(50)  		NULL,
	M_EXCLUSION_CD	VARCHAR(25) 	NULL,
	C_PATH	VARCHAR(700) 	  		NULL,
	C_SYMBOL	VARCHAR(50)	  		NULL
   );
   
ALTER TABLE i2b2metadata.eva_meta OWNER TO i2b2metadata;
CREATE INDEX META_FULLNAME_IDX_eva_meta ON i2b2metadata.EVA_META(C_FULLNAME);
CREATE INDEX META_APPLIED_PATH_IDX_eva_meta ON i2b2metadata.EVA_META(M_APPLIED_PATH);

TRUNCATE i2b2metadata.TABLE_ACCESS;
INSERT INTO i2b2metadata.TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD) VALUES('EVA_META', 'EVA_META', 'N', 0, '\ATC\', 'Arzneimittel (ATC)', 'N', 'CA', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\ATC\', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO i2b2metadata.TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD) VALUES('EVA_META', 'EVA_META', 'N', 0, '\ICD\', 'Diagnosen (ICD-10-GM)', 'N', 'CA', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\ICD\', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO i2b2metadata.TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD) VALUES('EVA_META', 'EVA_META', 'N', 0, '\PROVIDER\', 'Fachgruppen - Arzt', 'N', 'CA', NULL, NULL, NULL, 'provider_id', 'provider_dimension', 'provider_path', 'T', 'LIKE', '\PROVIDER\', NULL, NULL, NULL, NULL, NULL, NULL);
