DELETE FROM i2b2metadata.TABLE_ACCESS WHERE C_FULLNAME  LIKE '\\Stammdaten\\%';
INSERT INTO i2b2metadata.TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD)
  VALUES('EVA_META', 'EVA_META', 'N', 0, '\Stammdaten\', 'Stammdaten', 'N', 'CA', NULL, NULL, NULL, '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL);
DELETE FROM i2b2metadata.EVA_META WHERE C_FULLNAME = '\Stammdaten\';
INSERT INTO i2b2metadata.EVA_META (C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, M_APPLIED_PATH, UPDATE_DATE, C_PATH)
  VALUES (0, '\Stammdaten\', 'Stammdaten', 'N', 'CA', NULL, NULL, '', '', '', '', '', '', '', '2014-01-01', NULL);

  